apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- if .Values.image.caddy.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
{{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: 30m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
    nginx.ingress.kubernetes.io/proxy-buffering: 'on'
    nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 1024m
  name: ciso-assistant-{{ .Values.clientName }}
  labels:
    client: {{ .Values.clientName }}
    {{- include "common.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.clientName }}.{{ .Values.clusterDomain }}
    http:
      paths:
{{- if .Values.image.caddy.enabled }}
      - backend:
          service:
            name: ciso-assistant-{{ .Values.clientName }}
            port:
              number: 443
        path: /
        pathType: Prefix
{{- else }}
      - backend:
          service:
            name: ciso-assistant-{{ .Values.clientName }}
            port:
              number: 3000
        path: /
        pathType: Prefix
      - backend:
          service:
            name: ciso-assistant-{{ .Values.clientName }}
            port:
              number: 8000
        path: /api/
        pathType: Prefix
{{- end }}
